name: AI QA Daily Brief 

on:
  schedule:
    - cron: "0 12 * * *"

  workflow_dispatch:

jobs:
  send-news:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run AI QA Brief
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          TAVILY_API_KEY: ${{ secrets.TAVILY_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

        run: python main.py